import { ExpenseConstructorParams, ExpenseEntity } from './interface';
import { getCurrentMonth } from './config';

export default class Expense implements ExpenseEntity {
  id: ExpenseEntity['id'];
  user: ExpenseEntity['user'];
  year?: ExpenseEntity['year'] = new Date().getFullYear();
  type: ExpenseEntity['type'];
  paid: ExpenseEntity['paid'] = false;
  value?: ExpenseEntity['value'] = 0;
  total?: ExpenseEntity['total'] = 0;
  month?: ExpenseEntity['month'] = getCurrentMonth();
  group: ExpenseEntity['group'];
  active?: ExpenseEntity['active'] = true;
  supplier: ExpenseEntity['supplier'];
  category: ExpenseEntity['category'];
  total_paid?: ExpenseEntity['total_paid'] = 0;
  january?: ExpenseEntity['january'] = 0;
  february?: ExpenseEntity['february'] = 0;
  march?: ExpenseEntity['march'] = 0;
  april?: ExpenseEntity['april'] = 0;
  may?: ExpenseEntity['may'] = 0;
  june?: ExpenseEntity['june'] = 0;
  july?: ExpenseEntity['july'] = 0;
  august?: ExpenseEntity['august'] = 0;
  september?: ExpenseEntity['september'] = 0;
  october?: ExpenseEntity['october'] = 0;
  november?: ExpenseEntity['november'] = 0;
  december?: ExpenseEntity['december'] = 0;
  january_paid?: ExpenseEntity['january_paid'] = false;
  february_paid?: ExpenseEntity['february_paid'] = false;
  march_paid?: ExpenseEntity['march_paid'] = false;
  april_paid?: ExpenseEntity['april_paid'] = false;
  may_paid?: ExpenseEntity['may_paid'] = false;
  june_paid?: ExpenseEntity['june_paid'] = false;
  july_paid?: ExpenseEntity['july_paid'] = false;
  august_paid?: ExpenseEntity['august_paid'] = false;
  september_paid?: ExpenseEntity['september_paid'] = false;
  october_paid?: ExpenseEntity['october_paid'] = false;
  november_paid?: ExpenseEntity['november_paid'] = false;
  december_paid?: ExpenseEntity['december_paid'] = false;
  created_at: ExpenseEntity['created_at'];
  updated_at: ExpenseEntity['updated_at'];
  deleted_at: ExpenseEntity['deleted_at'];
  description?: ExpenseEntity['description'];
  instalment_number?: ExpenseEntity['instalment_number'] = 1;
  constructor(params?: ExpenseConstructorParams) {
    this.id = params?.id ?? this.id;
    this.user = params?.user;
    this.year = params?.year ?? this.year;
    this.type = params?.type ?? this.type;
    this.paid = params?.paid ?? this.paid;
    this.value = params?.value ?? this.value;
    this.total = params?.total ?? this.total;
    this.month = params?.month ?? this.month;
    this.group = params?.group;
    this.active = params?.active ?? this.active;
    this.supplier = params?.supplier;
    this.category = params?.category;
    this.type = params?.type;
    this.total_paid = params?.total_paid ?? this.total_paid;
    this.january = params?.january ?? this.january;
    this.february = params?.february ?? this.february;
    this.march = params?.march ?? this.march;
    this.april = params?.april ?? this.april;
    this.may = params?.may ?? this.may;
    this.june = params?.june ?? this.june;
    this.july = params?.july ?? this.july;
    this.august = params?.august ?? this.august;
    this.september = params?.september ?? this.september;
    this.october = params?.october ?? this.october;
    this.november = params?.november ?? this.november;
    this.december = params?.december ?? this.december;
    this.january_paid = params?.january_paid ?? this.january_paid;
    this.february_paid = params?.february_paid ?? this.february_paid;
    this.march_paid = params?.march_paid ?? this.march_paid;
    this.april_paid = params?.april_paid ?? this.april_paid;
    this.may_paid = params?.may_paid ?? this.may_paid;
    this.june_paid = params?.june_paid ?? this.june_paid;
    this.july_paid = params?.july_paid ?? this.july_paid;
    this.august_paid = params?.august_paid ?? this.august_paid;
    this.september_paid = params?.september_paid ?? this.september_paid;
    this.october_paid = params?.october_paid ?? this.october_paid;
    this.november_paid = params?.november_paid ?? this.november_paid;
    this.december_paid = params?.december_paid ?? this.december_paid;
    this.description = params?.description ?? this.description;
    this.instalment_number =
      params?.instalment_number ?? this.instalment_number;
    this.created_at = params?.created_at ?? this.created_at;
    this.updated_at = params?.updated_at ?? this.updated_at;
    this.deleted_at = params?.deleted_at ?? this.deleted_at;
  }
}
