import React from 'react';

import {
  FaAnchor,
  FaAndroid,
  FaArrowDown,
  FaArrowLeft,
  FaArrowRight,
  FaBatteryFull,
  FaBed,
  FaBluetooth,
  FaBolt,
  FaBook,
  FaBookmark,
  FaBrush,
  FaCamera,
  FaChair,
  FaChargingStation,
  FaCheck,
  FaChevronLeft,
  FaChevronRight,
  FaChurch,
  FaCloud,
  FaCode,
  FaComment,
  FaCompress,
  FaCookie,
  FaCreditCard,
  FaDownload,
  FaEgg,
  FaEject,
  FaExpand,
  FaEye,
  FaEyeSlash,
  FaFacebook,
  FaFilter,
  FaFingerprint,
  FaFireExtinguisher,
  FaFlag,
  FaFolder,
  FaFolderOpen,
  FaForward,
  FaGamepad,
  FaGavel,
  FaGoogle,
  FaHamburger,
  FaHandshake,
  FaHeadphones,
  FaHotel,
  FaImage,
  FaInbox,
  FaInfo,
  FaKey,
  FaKeyboard,
  FaLaptop,
  FaLightbulb,
  FaLink,
  FaList,
  FaLock,
  FaLockOpen,
  FaMap,
  FaPalette,
  FaPause,
  FaPhone,
  FaPowerOff,
  FaPrint,
  FaReact,
  FaReceipt,
  FaRegCalendarAlt,
  FaRegHeart,
  FaRegLightbulb,
  FaRegNewspaper,
  FaRegTimesCircle,
  FaRegUser,
  FaReply,
  FaReplyAll,
  FaRocket,
  FaRoute,
  FaSchool,
  FaShareAlt,
  FaShower,
  FaSort,
  FaStar,
  FaStarHalfAlt,
  FaStop,
  FaStore,
  FaTabletAlt,
  FaTag,
  FaTerminal,
  FaTrain,
  FaTransgender,
  FaTv,
  FaUmbrella,
  FaUpload,
  FaVolumeOff,
  FaWallet,
  FaWarehouse,
} from 'react-icons/fa';

import type { TIconGroupIcons } from '../interface';

export const faGroup: TIconGroupIcons = {
  tv: <FaTv />,
  tag: <FaTag />,
  key: <FaKey />,
  map: <FaMap />,
  egg: <FaEgg />,
  eye: <FaEye />,
  bed: <FaBed />,
  user: <FaRegUser />,
  lamp: <FaRegLightbulb />,
  star: undefined,
  bolt: <FaBolt />,
  book: <FaBook />,
  info: <FaInfo />,
  code: <FaCode />,
  like: <FaRegHeart />,
  exit: undefined,
  flag: <FaFlag />,
  link: <FaLink />,
  list: <FaList />,
  lock: <FaLock />,
  sort: <FaSort />,
  stop: <FaStop />,
  brush: <FaBrush />,
  chair: <FaChair />,
  check: <FaCheck />,
  close: <FaRegTimesCircle />,
  react: <FaReact />,
  phone: <FaPhone />,
  cloud: <FaCloud />,
  hotel: <FaHotel />,
  image: <FaImage />,
  inbox: <FaInbox />,
  gavel: <FaGavel />,
  eject: <FaEject />,
  pause: <FaPause />,
  print: <FaPrint />,
  store: <FaStore />,
  reply: <FaReply />,
  train: <FaTrain />,
  route: <FaRoute />,
  share: <FaShareAlt />,
  church: <FaChurch />,
  google: <FaGoogle />,
  camera: <FaCamera />,
  anchor: <FaAnchor />,
  folder: <FaFolder />,
  expand: <FaExpand />,
  filter: <FaFilter />,
  cookie: <FaCookie />,
  laptop: <FaLaptop />,
  wallet: <FaWallet />,
  upload: <FaUpload />,
  school: <FaSchool />,
  rocket: <FaRocket />,
  shower: <FaShower />,
  tablet: <FaTabletAlt />,
  android: <FaAndroid />,
  forward: <FaForward />,
  comment: <FaComment />,
  gamepad: <FaGamepad />,
  palette: <FaPalette />,
  receipt: <FaReceipt />,
  confirm: undefined,
  warning: undefined,
  'arrow-up': undefined,
  facebook: <FaFacebook />,
  calendar: <FaRegCalendarAlt />,
  document: undefined,
  bookmark: <FaBookmark />,
  compress: <FaCompress />,
  terminal: <FaTerminal />,
  download: <FaDownload />,
  keyboard: <FaKeyboard />,
  umbrella: <FaUmbrella />,
  warehouse: <FaWarehouse />,
  lightbulb: <FaLightbulb />,
  'lock-open': <FaLockOpen />,
  handshake: <FaHandshake />,
  'power-off': <FaPowerOff />,
  'reply-all': <FaReplyAll />,
  newspaper: <FaRegNewspaper />,
  'star-half': <FaStarHalfAlt />,
  bluetooth: <FaBluetooth />,
  dashboard: undefined,
  hamburger: <FaHamburger />,
  'eye-close': <FaEyeSlash />,
  'arrow-down': <FaArrowDown />,
  'arrow-left': <FaArrowLeft />,
  headphones: <FaHeadphones />,
  'volume-off': <FaVolumeOff />,
  transgender: <FaTransgender />,
  'folder-open': <FaFolderOpen />,
  'credit-card': <FaCreditCard />,
  fingerprint: <FaFingerprint />,
  'arrow-right': <FaArrowRight />,
  'battery-full': <FaBatteryFull />,
  'star-filled': <FaStar />,
  'chevron-left': <FaChevronLeft />,
  'chevron-right': <FaChevronRight />,
  'arrow-up-outline': undefined,
  'charging-station': <FaChargingStation />,
  'arrow-down-outline': undefined,
  'fire-extinguisher': <FaFireExtinguisher />,
};