import { FaEye } from 'react-icons/fa6';

import type { TIconGroupIcons } from '../interface';

export const fa6Group: TIconGroupIcons = {
  eye: <FaEye />,
  user: undefined,
  lamp: undefined,
  star: undefined,
  info: undefined,
  like: undefined,
  exit: undefined,
  check: undefined,
  close: undefined,
  error: undefined,
  react: undefined,
  phone: undefined,
  google: undefined,
  camera: undefined,
  confirm: undefined,
  success: undefined,
  warning: undefined,
  'arrow-up': undefined,
  facebook: undefined,
  calendar: undefined,
  document: undefined,
  'star-half': undefined,
  dashboard: undefined,
  hamburger: undefined,
  'eye-close': undefined,
  'arrow-down': undefined,
  'arrow-right': undefined,
  'star-filled': undefined,
  'arrow-up-outline': undefined,
  'arrow-down-outline': undefined,
};