import React from 'react';

import type { Metadata } from 'next';

import '@repo/tokens/dist/geek/css/_variables.css';
import '../styles/global.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <h1>LAYOUT</h1>
        {children}
      </body>
    </html>
  );
}
