import {
  MdOutlineArrowDropDown,
  MdOutlineArrowDropUp,
  MdOutlineInfo,
  MdOutlineKeyboardArrowDown,
  MdOutlineKeyboardArrowRight,
  MdOutlineKeyboardArrowUp,
  MdOutlineSpaceDashboard,
} from 'react-icons/md';

import type { TIconGroupIcons } from '../interface';

export const mdGroup: TIconGroupIcons = {
  eye: undefined,
  user: undefined,
  lamp: undefined,
  star: undefined,
  info: <MdOutlineInfo />,
  like: undefined,
  exit: undefined,
  check: undefined,
  close: undefined,
  error: undefined,
  react: undefined,
  phone: undefined,
  google: undefined,
  camera: undefined,
  confirm: undefined,
  success: undefined,
  warning: undefined,
  'arrow-up': <MdOutlineArrowDropUp />,
  facebook: undefined,
  calendar: undefined,
  document: undefined,
  'star-half': undefined,
  dashboard: <MdOutlineSpaceDashboard />,
  hamburger: undefined,
  'eye-close': undefined,
  'arrow-down': <MdOutlineArrowDropDown />,
  'arrow-right': <MdOutlineKeyboardArrowRight />,
  'star-filled': undefined,
  'arrow-up-outline': <MdOutlineKeyboardArrowUp />,
  'arrow-down-outline': <MdOutlineKeyboardArrowDown />,
};