import React from 'react';
import {
  GiAnchor,
  GiBattery100,
  GiBed,
  GiBigEgg,
  GiBookCover,
  GiBookmarklet,
  GiCalendar,
  GiCancel,
  GiCharging,
  GiChatBubble,
  GiChecklist,
  GiCheckMark,
  GiChurch,
  GiCloudDownload,
  GiCloudUpload,
  GiConfirmed,
  GiContract,
  GiCookie,
  GiExitDoor,
  GiExpand,
  GiEyelashes,
  GiEyeOfHorus,
  GiFastForwardButton,
  GiFingerPrint,
  GiFireExtinguisher,
  GiFlyingFlag,
  GiFullFolder,
  GiGamepad,
  GiGavel,
  GiHamburger,
  GiHeadphones,
  GiHearts,
  GiHomeGarage,
  GiInfo,
  GiKey,
  GiKeyboard,
  GiLaptop,
  GiLaserWarning,
  GiLightBulb,
  GiLinkedRings,
  GiNewspaper,
  GiOpenFolder,
  GiPadlock,
  GiPadlockOpen,
  GiPaintBrush,
  GiPalette,
  GiPauseButton,
  GiPerson,
  GiPhone,
  GiPhotoCamera,
  GiPowerButton,
  GiPriceTag,
  GiReceiveMoney,
  GiRocket,
  GiSchoolBag,
  GiShakingHands,
  GiShare,
  GiShower,
  GiStopSign,
  GiSunCloud,
  GiSwipeCard,
  GiTablet,
  GiThunderStruck,
  GiTreasureMap,
  GiTv,
  GiUmbrella,
  GiWallet,
  GiWoodenChair,
} from 'react-icons/gi';

import type { TIconGroupIcons } from '../interface';

export const giGroup: TIconGroupIcons = {
  tv: <GiTv />,
  box: undefined,
  tag: <GiPriceTag />,
  key: <GiKey />,
  map: <GiTreasureMap />,
  egg: <GiBigEgg />,
  eye: <GiEyeOfHorus />,
  bed: <GiBed />,
  user: <GiPerson />,
  lamp: <GiLightBulb />,
  star: undefined,
  bolt: <GiThunderStruck />,
  book: <GiBookCover />,
  info: <GiInfo />,
  code: undefined,
  like: <GiHearts />,
  exit: <GiExitDoor />,
  flag: <GiFlyingFlag />,
  link: <GiLinkedRings />,
  list: <GiChecklist />,
  lock: <GiPadlock />,
  sort: undefined,
  stop: <GiStopSign />,
  home: undefined,
  group: undefined,
  brush: <GiPaintBrush />,
  chair: <GiWoodenChair />,
  check: <GiCheckMark />,
  close: <GiCancel />,
  react: undefined,
  phone: <GiPhone />,
  cloud: <GiSunCloud />,
  hotel: undefined,
  image: undefined,
  inbox: undefined,
  gavel: <GiGavel />,
  eject: undefined,
  pause: <GiPauseButton />,
  print: undefined,
  store: undefined,
  reply: undefined,
  train: undefined,
  route: undefined,
  share: <GiShare />,
  config: undefined,
  church: <GiChurch />,
  google: undefined,
  camera: <GiPhotoCamera />,
  anchor: <GiAnchor />,
  folder: <GiFullFolder />,
  expand: <GiExpand />,
  filter: undefined,
  cookie: <GiCookie />,
  laptop: <GiLaptop />,
  wallet: <GiWallet />,
  upload: <GiCloudUpload />,
  school: <GiSchoolBag />,
  rocket: <GiRocket />,
  shower: <GiShower />,
  tablet: <GiTablet />,
  android: undefined,
  forward: <GiFastForwardButton />,
  comment: <GiChatBubble />,
  gamepad: <GiGamepad />,
  palette: <GiPalette />,
  receipt: <GiReceiveMoney />,
  confirm: <GiConfirmed />,
  warning: <GiLaserWarning />,
  expense: undefined,
  category: undefined,
  'user-tie': undefined,
  'arrow-up': undefined,
  facebook: undefined,
  calendar: <GiCalendar />,
  document: undefined,
  bookmark: <GiBookmarklet />,
  compress: <GiContract />,
  terminal: undefined,
  download: <GiCloudDownload />,
  keyboard: <GiKeyboard />,
  umbrella: <GiUmbrella />,
  'sign-out': undefined,
  warehouse: <GiHomeGarage />,
  lightbulb: <GiLightBulb />,
  'lock-open': <GiPadlockOpen />,
  handshake: <GiShakingHands />,
  'power-off': <GiPowerButton />,
  'reply-all': undefined,
  newspaper: <GiNewspaper />,
  'star-half': undefined,
  bluetooth: undefined,
  dashboard: undefined,
  hamburger: <GiHamburger />,
  'eye-close': <GiEyelashes />,
  'arrow-down': undefined,
  'arrow-left': undefined,
  headphones: <GiHeadphones />,
  'volume-off': undefined,
  transgender: undefined,
  'folder-open': <GiOpenFolder />,
  'credit-card': <GiSwipeCard />,
  fingerprint: <GiFingerPrint />,
  'arrow-right': undefined,
  'battery-full': <GiBattery100 />,
  'star-filled': undefined,
  'chevron-up': undefined,
  'chevron-left': undefined,
  'chevron-down': undefined,
  'chevron-right': undefined,
  'arrow-up-outline': undefined,
  'charging-station': <GiCharging />,
  'arrow-down-outline': undefined,
  'fire-extinguisher': <GiFireExtinguisher />,
};
